-- MySQL Script generated by MySQL Workbench
-- Fri Apr 15 12:47:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema olx_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema olx_database
-- -----------------------------------------------------
DROP DATABASE IF EXISTS olx_database;
CREATE SCHEMA IF NOT EXISTS `olx_database` DEFAULT CHARACTER SET utf8 ;
USE `olx_database` ;

-- -----------------------------------------------------
-- Table `olx_database`.`dm_tempo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx_database`.`dm_tempo` (
  `ID_TEMPO` INT NOT NULL AUTO_INCREMENT,
  `ANO` INT NULL,
  `MES` INT NULL,
  `DIA` INT NULL,
  `HORA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_TEMPO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx_database`.`dm_local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx_database`.`dm_local` (
  `ID_LOCAL` INT NOT NULL AUTO_INCREMENT,
  `ESTADO` VARCHAR(45) NULL,
  `CIDADE` VARCHAR(45) NULL,
  `BAIRRO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_LOCAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx_database`.`dm_celular`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx_database`.`dm_celular` (
  `ID_CELULAR` INT NOT NULL AUTO_INCREMENT,
  `MARCA` VARCHAR(45) NULL,
  `MODELO` VARCHAR(255) NULL,
  `CONDICAO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_CELULAR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx_database`.`dm_anunciante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx_database`.`dm_anunciante` (
  `ID_ANUNCIANTE` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_ANUNCIANTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx_database`.`dm_fato_anuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx_database`.`dm_fato_anuncios` (
  `DM_CELULAR_ID_CELULAR` INT NOT NULL,
  `DM_TEMPO_ID_TEMPO` INT NOT NULL,
  `DM_LOCAL_ID_LOCAL` INT NOT NULL,
  `DM_ANUNCIANTE_ID_ANUNCIANTE` INT NOT NULL,
  `PRECO` VARCHAR(45) NULL,
  PRIMARY KEY (`DM_CELULAR_ID_CELULAR`, `DM_TEMPO_ID_TEMPO`, `DM_LOCAL_ID_LOCAL`, `DM_ANUNCIANTE_ID_ANUNCIANTE`),
  INDEX `fk_DM_FATO_ANUNCIOS_DM_TEMPO1_idx` (`DM_TEMPO_ID_TEMPO` ASC) VISIBLE,
  INDEX `fk_DM_FATO_ANUNCIOS_DM_LOCAL1_idx` (`DM_LOCAL_ID_LOCAL` ASC) VISIBLE,
  INDEX `fk_DM_FATO_ANUNCIOS_DM_ANUNCIANTE1_idx` (`DM_ANUNCIANTE_ID_ANUNCIANTE` ASC) VISIBLE,
  CONSTRAINT `fk_DM_FATO_ANUNCIOS_DM_CELULAR`
    FOREIGN KEY (`DM_CELULAR_ID_CELULAR`)
    REFERENCES `olx_database`.`dm_celular` (`ID_CELULAR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DM_FATO_ANUNCIOS_DM_TEMPO1`
    FOREIGN KEY (`DM_TEMPO_ID_TEMPO`)
    REFERENCES `olx_database`.`dm_tempo` (`ID_TEMPO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DM_FATO_ANUNCIOS_DM_LOCAL1`
    FOREIGN KEY (`DM_LOCAL_ID_LOCAL`)
    REFERENCES `olx_database`.`dm_local` (`ID_LOCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DM_FATO_ANUNCIOS_DM_ANUNCIANTE1`
    FOREIGN KEY (`DM_ANUNCIANTE_ID_ANUNCIANTE`)
    REFERENCES `olx_database`.`dm_anunciante` (`ID_ANUNCIANTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `olx_database`.`tmp_etl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `olx_database`.`tmp_etl` (
  `ID_TMP_ETL` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  `ESTADO` VARCHAR(45) NULL,
  `CIDADE` VARCHAR(45) NULL,
  `BAIRRO` VARCHAR(45) NULL,
  `ANO` INT NULL,
  `MES` INT NULL,
  `DIA` INT NULL,
  `HORA` VARCHAR(45) NULL,
  `MARCA` VARCHAR(45) NULL,
  `MODELO` VARCHAR(255) NULL,
  `CONDICAO` VARCHAR(45) NULL,
  `PRECO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_TMP_ETL`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
